server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5167/blog_oauth2_db
    username: rathana
    password: Rathana$10
    driver-class-name: org.postgresql.Driver

